@extends('frontoffice.layouts.outter_app_layout')

@section('content')
    @include('frontoffice.home.parts.hero')
    @include('frontoffice.home.parts.feature')
    @include('frontoffice.home.parts.category')
    @include('frontoffice.home.parts.course')
    @include('frontoffice.home.parts.course')
    @include('frontoffice.home.parts.funfact')
    @include('frontoffice.home.parts.cta')
    @include('frontoffice.home.parts.testimonial')
    @include('frontoffice.home.parts.about')
    @include('frontoffice.home.parts.register')
    @include('frontoffice.home.parts.client')
    @include('frontoffice.home.parts.blog')
    @include('frontoffice.home.parts.get_started')
    @include('frontoffice.home.parts.subscriber')
@endsection